name: Отмена предыдущих тестов
on:
  push:
    branches:
      - master

jobs:
  Cancel:
    name: 'Отмена Ненужных Билдов'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@01ce38bf961b4e243a6342cbade0dbc8ba3f0432
        with:
          workflow_id: 9143745, 5560543
          access_token: ${{ github.token }}
