name: Тестирование

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master220
env:
  BYOND_MAJOR: "514"
  BYOND_MINOR: "1588"
  SPACEMAN_DMM_VERSION: suite-1.7.3

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  PreFlight:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: paths-filter
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        id: filter
        with:
          filters: .github/workflow-config/preflight-filters.yml
    outputs:
      dm: ${{ steps.filter.outputs.dm }}
  DreamChecker:
    runs-on: ubuntu-latest
    needs: PreFlight
    if: needs.PreFlight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: Setup Cache
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84
        with:
          path: ~/spaceman_dmm/${{ env.SPACEMAN_DMM_VERSION }}
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install Dreamchecker
        run:  scripts/install-spaceman-dmm.sh dreamchecker
      - name: Run Dreamchecker
        run: ~/dreamchecker
  Code:
    runs-on: ubuntu-latest
    needs: DreamChecker
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: Setup Cache
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install Dependencies
        run: sudo apt-get install -y uchardet
      - name: Run Tests
        env:
          TEST: CODE
        run: test/run-test.sh
  # Maps:
  #   runs-on: ubuntu-latest
  #   needs: DreamChecker
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       map_path: [example, sierra, away_sites_testing]
  #   steps:
  #     - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
  #     - name: Setup Cache
  #       uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84
  #       with:
  #         path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
  #         key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
  #     - name: Run Tests
  #       env:
  #         TEST: MAP
  #         MAP_PATH: ${{ matrix.map_path }}
  #       run: test/run-test.sh
